defunct:
  - SERVICEDESK-MISROUTEDTICKET
  - MECM
  - BILLING
  - PURCHASING
  - BADG
  - WEBTECH
  - PLANNING
  - ECOTIMESUPPORT
  - CCR-SUPPORT
  - LAPTOPLOANERS
  - INTUNE
  - MEDIATEACHLAB
  - UCSD-AH-SUPPORT
  - STAFFADMIN
  - DATAWAREHOUSE
  - ENDPOINTSTOREKEEPER
  - MIDDLEWAREINTEGRATION
  - TSMT
  - STAFFHR
  - CHANGEMANAGEMENT
  - FACILITIESMGMT
  - CONTINUITYPLANNING
  - ENTERPRISEARCHITECTURE
  - LSS-SUPPORT
  - MEDIASERVICESMGMT
  - SERVICEMGMTOFFICE
  - FINANCIALMAINFRAME
  - PATCHMGMT
  - WORKPLACETECHSERVICES
  - PROBLEMMANAGEMENT
  - FIM-CAD
  - WALKME
  - RMP
  - RIS
  - PRODUCTIONCONTROL
  - SHAREPOINTSUPPORT
  - DATACENTERTPC
  - INTERFOLIO
  - COMMUNICATIONSANDOUTREACH
  - DATACENTERTPC
  - NGNBILLINGSUPPORT
  - STUDENTREPORTING
  - OUTSIDEPLANT-NODEROOM
  - FAS-SFP
  - TELECOMBILLINGSUPPORT
  - ENDPOINTSUPPORT
  - BUSINESSINTELLIGENCE
  - NETWORKARCHITECTURE
  - MEDIAEVENT
  - SDMI

val_size: 0.1
random_state: 42
max_repeats: 5
