model_name: microsoft/deberta-v3-base
task: ticketclass
project: ticket-classifier
batch_size: 16
lr: 3.0e-5
weight_decay: 0.01
gradient_accumulation: 4
num_epochs: 3
scheduler: cosine
warmup_ratio: 0.05
save_steps: 2000
checkpoint_dir: ../models
use_wandb: true
