services:
  app:
    build: .
    container_name: servicedeskassistant
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  qdrant_data:
